"""Step 9 of 9: 将 Python AI 生成的 COPILOT_TOOLS.md 写入 clone，commit → push → PR → auto-merge。

上游输入：
  /tmp/ai_tools/installed_tools.json  — install_selected.py 输出的摘要
  README_CONTENT_FILE env             — generate_tools_readme.py 输出的文件路径

操作流程：
  1. 将 AI 生成的 COPILOT_TOOLS.md 写入克隆目录
  2. git add --all → commit → push
  3. 在目标仓库创建 PR（已有打开 PR 则复用）
  4. 启用 PR 自动合并（Squash，仓库需开启 Auto-merge）
"""

from __future__ import annotations

import datetime
import json
import logging
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from github_api import GitHubAPI

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)

TMP_DIR = Path("/tmp/ai_tools")
CLONE_DIR = Path("/tmp/target-repo-clone")
BOT_EMAIL = "github-actions[bot]@users.noreply.github.com"


def _git(args: list[str], cwd: str = str(CLONE_DIR)) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", cwd, *args], check=True, capture_output=True)


def _has_staged_changes() -> bool:
    result = subprocess.run(
        ["git", "-C", str(CLONE_DIR), "diff", "--cached", "--quiet"],
        capture_output=True,
    )
    return result.returncode != 0


def _simple_readme(tools: list[dict]) -> str:
    """AI 生成失败时的兜底 README。"""
    lines = [
        "# GitHub Copilot Tools\n\n",
        "Auto-generated overview of Copilot tools installed in this repository.\n\n",
    ]
    headers = {
        "instruction": "## 📋 Instructions\n\n",
        "agent": "## 🤖 Agents\n\n",
        "skill": "## ⚡ Skills & Prompts\n\n",
    }
    by_type: dict[str, list[dict]] = {}
    for t in tools:
        by_type.setdefault(t["type"], []).append(t)
    for tool_type, header in headers.items():
        if tool_type not in by_type:
            continue
        lines.append(header)
        for t in by_type[tool_type]:
            lines.append(f"### {t['name']}\n`{t['path']}`\n\n")
    lines.append("---\n*Auto-generated by repos-ai-tools-maintain.*\n")
    return "".join(lines)


def _build_pr_body(
    summary: dict,
    maintenance_repo: str,
    today: str,
) -> str:
    tools = summary.get("installed_this_run", [])
    new_count = summary["new_count"]
    updated_count = summary["updated_count"]
    from_defaults = summary["from_defaults"]

    rows = "\n".join(
        "| {emoji} `{name}` | {t} | {action} | `{path}` |".format(
            emoji={"instruction": "📋", "agent": "🤖", "skill": "⚡"}.get(t["type"], "📄"),
            name=t["name"],
            t=t["type"],
            action="🆕 新增" if t.get("_action") == "new" else "🔄 更新",
            path=t.get("path", "") or "—",
        )
        for t in tools
    ) or "| *(仅更新文档)* | — | — | — |"

    changed_paths = sorted(
        {
            t.get("path", "")
            for t in tools
            if t.get("path")
        }
        | {".github/TOOLS_INDEX.md", ".github/COPILOT_TOOLS.md"}
    )
    changed_path_lines = "\n".join(f"- `{path}`" for path in changed_paths)

    source_note = "built-in recommended Copilot tools" if from_defaults else "GitHub trending repositories"

    return f"""## 🤖 Automated Copilot Tools Update — {today}

> Auto-generated by [repos-ai-tools-maintain](https://github.com/{maintenance_repo})
> powered by Python scripts + **GitHub Models API**.

### 📦 Changed tools ({new_count} new · {updated_count} updated)

| Tool | Type | Action | Path |
|------|------|--------|------|
{rows}

### 🔍 Discovery process

1. `prepare_target_repo.py` — exported target repository context for downstream AI steps
2. `search_tool_repos.py` — used Python + GitHub Models to rank promising AI tool repositories
3. `scan_ai_candidates.py` — scanned AI-selected repositories for Copilot tools
4. `analyze_relevance.py` — used Python + GitHub Models to judge relevance for this repository
5. `install_selected.py` — {"installed built-in recommended tools (no trending match)" if from_defaults else "installed/updated matching tools"}
6. `annotate_installed_tools.py` — used Python + GitHub Models to classify tools and generate **Chinese annotations**
7. `apply_annotations.py` — wrote Chinese comment headers into tool files + created `.github/TOOLS_INDEX.md`
8. `generate_tools_readme.py` — used Python + GitHub Models to generate `.github/COPILOT_TOOLS.md`
9. `commit_pr.py` — committed changes and opened this PR with auto-merge enabled

### 📁 Changed files

{changed_path_lines}

### ✅ Review checklist

- [ ] 查看各工具文件头部的 `<!-- 中文注释 -->` 是否准确
- [ ] 阅读 `.github/TOOLS_INDEX.md` 确认分类合理
- [ ] Read `.github/COPILOT_TOOLS.md` for the full usage guide
- [ ] Test tools with GitHub Copilot in VS Code
- [ ] Remove any tools that don't fit your workflow

---
*🤖 Generated from {source_note} via [repos-ai-tools-maintain](https://github.com/{maintenance_repo})*
"""


def main() -> None:
    installed_path = TMP_DIR / "installed_tools.json"
    if not installed_path.exists():
        raise SystemExit("❌  installed_tools.json not found — run install_selected.py first")

    summary = json.loads(installed_path.read_text(encoding="utf-8"))
    target_repo = summary["target_repo"]
    branch_name = summary["branch_name"]
    default_branch = summary["default_branch"]
    today = datetime.date.today().isoformat()
    from_defaults = summary["from_defaults"]
    new_count = summary["new_count"]
    updated_count = summary["updated_count"]
    all_tools = summary.get("all_tools", [])

    target_token = (
        os.environ.get("RESOLVED_ORG_TOKEN", "").strip()
        or os.environ.get("TARGET_REPO_TOKEN", "").strip()
    )
    if not target_token:
        raise SystemExit("❌  No PAT available for git ops")

    maintenance_repo = os.environ.get(
        "GITHUB_REPOSITORY", "knewbeing/repos-ai-tools-maintain"
    )

    # ── 写入 COPILOT_TOOLS.md ───────────────────────────────────────────
    # README_CONTENT_FILE 由 generate_tools_readme.py 输出
    readme_file = os.environ.get("README_CONTENT_FILE", "").strip()
    if readme_file and Path(readme_file).exists():
        readme_content = Path(readme_file).read_text(encoding="utf-8")
        logger.info("从 AI 输出文件读取 COPILOT_TOOLS.md 内容 (%d 字节)", len(readme_content))
    else:
        logger.warning("README_CONTENT_FILE 未提供，使用简单模板")
        readme_content = _simple_readme(all_tools)

    readme_path = CLONE_DIR / ".github" / "COPILOT_TOOLS.md"
    readme_path.parent.mkdir(parents=True, exist_ok=True)
    readme_path.write_text(readme_content, encoding="utf-8")

    # ── Git: add → commit → push ────────────────────────────────────────
    _git(["add", "--all"])

    if not _has_staged_changes():
        logger.info("暂存区无变更（工具与文档均已是最新），退出。")
        return

    tool_summary = f"{new_count} new, {updated_count} updated" if (new_count or updated_count) else "docs only"
    source = "built-in recommended tools" if from_defaults else "GitHub trending"
    commit_msg = (
        f"chore: update ai tools [{today}] ({tool_summary})\n\n"
        f"Installed from {source}\n\n"
        f"Co-authored-by: github-actions[bot] <{BOT_EMAIL}>"
    )
    _git(["commit", "-m", commit_msg])

    logger.info("正在推送分支 '%s'…", branch_name)
    _git(["push", "--set-upstream", "origin", branch_name])

    # ── 创建 PR（已有则复用）+ 启用自动合并 ─────────────────────────────
    api = GitHubAPI(target_token)

    existing_pr = api.get_open_pr(target_repo, branch_name, default_branch)
    if existing_pr:
        pr = existing_pr
        logger.info("已存在打开的 PR，复用: %s", pr["html_url"])
    else:
        pr = api.create_pr(
            repo=target_repo,
            title=(
                f"🤖 Update AI tools [{today}]"
                f"{'  (recommended defaults)' if from_defaults else ''}"
            ),
            body=_build_pr_body(summary, maintenance_repo, today),
            head=branch_name,
            base=default_branch,
        )
        logger.info("✅  PR 已创建: %s", pr["html_url"])

    # 启用 PR 自动合并（Squash），仓库需在 Settings → General 开启 Auto-merge
    pr_node_id = pr.get("node_id")
    if pr_node_id and api.enable_pr_auto_merge(pr_node_id, merge_method="SQUASH"):
        logger.info("✅  已启用 PR 自动合并 (SQUASH): %s", pr["html_url"])
    else:
        logger.warning(
            "⚠️  未能启用 PR 自动合并"
            "（请确认仓库已开启 Auto-merge 且 token 具有 pull_requests 写权限）"
        )


if __name__ == "__main__":
    main()
