"""Main orchestration script for the daily Copilot tools discovery workflow."""

from __future__ import annotations

import datetime
import json
import logging
import os
import subprocess
import sys
import tempfile
from pathlib import Path

# Make sibling modules importable regardless of working directory
sys.path.insert(0, str(Path(__file__).parent))

from analyze_tools import analyze_tool_relevance
from fetch_trending import fetch_repo_copilot_tools, fetch_trending_repos
from github_api import GitHubAPI
from install_tools import install_tools
from organize_readme import organize_and_generate_readme

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)

_ROOT = Path(__file__).parent.parent.parent  # repo root
_REPOS_FILE = _ROOT / "repos.json"
_BOT_EMAIL = "github-actions[bot]@users.noreply.github.com"
_BOT_NAME = "github-actions[bot]"


# ------------------------------------------------------------------ #
# Helpers                                                              #
# ------------------------------------------------------------------ #


def _load_config() -> dict:
    with open(_REPOS_FILE) as fh:
        return json.load(fh)


def pick_target_repo() -> tuple[str, str]:
    """Round-robin repo selection. Returns (repo_full_name, token_secret_name)."""
    config = _load_config()
    entries: list = config.get("repositories", [])
    if not entries:
        raise SystemExit("❌  No repositories in repos.json. Add at least one entry.")
    default_secret = config.get("settings", {}).get("default_token_secret", "TARGET_REPO_TOKEN")

    idx = (datetime.date.today().timetuple().tm_yday - 1) % len(entries)
    entry = entries[idx]

    if isinstance(entry, str):
        return entry, default_secret
    # Object form: {"repo": "org/name", "token_secret": "SECRET_NAME"}
    return entry["repo"], entry.get("token_secret", default_secret)


def resolve_token(secret_name: str) -> str:
    """Read the env var *secret_name*. Raise SystemExit if missing or empty."""
    value = os.environ.get(secret_name, "").strip()
    if not value:
        raise SystemExit(
            f"❌  Secret '{secret_name}' is not set in the workflow environment.\n"
            f"    Add it to repos.json and declare it in the workflow YAML env: block."
        )
    logger.info("Using token from secret '%s'", secret_name)
    return value


def _run(cmd: list[str], cwd: str | None = None) -> None:
    subprocess.run(cmd, check=True, capture_output=True, cwd=cwd)


def _git(args: list[str], cwd: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", cwd, *args], check=True, capture_output=True)


def _setup_git(tmpdir: str) -> None:
    _git(["config", "user.email", _BOT_EMAIL], tmpdir)
    _git(["config", "user.name", _BOT_NAME], tmpdir)


def _has_staged_changes(tmpdir: str) -> bool:
    result = subprocess.run(
        ["git", "-C", tmpdir, "diff", "--cached", "--quiet"], capture_output=True
    )
    return result.returncode != 0  # non-zero → there are staged changes


def _build_pr_body(installed: list[dict], target_repo: str, today: str) -> str:
    maintenance_repo = os.environ.get("GITHUB_REPOSITORY", "knewbeing/repos-ai-tools-maintain")
    rows = "\n".join(
        "| {emoji} `{name}` | {type} | [{src}](https://github.com/{src}) |".format(
            emoji={"instruction": "📋", "agent": "🤖", "skill": "⚡"}.get(t["type"], "📄"),
            name=t["name"],
            type=t["type"],
            src=t.get("source_repo", ""),
        )
        for t in installed
    )

    return f"""## 🤖 Automated Copilot Tools Update — {today}

This PR was automatically generated by the [daily Copilot tools maintenance workflow](https://github.com/{maintenance_repo}).

### 📦 Installed tools ({len(installed)})

| Tool | Type | Source |
|------|------|--------|
{rows}

### 🔍 Discovery process

1. Fetched the top 10 trending repositories on GitHub
2. Scanned each for Copilot tools (instructions, agents, prompts)
3. Used AI (GPT-4o-mini via GitHub Models) to judge relevance for `{target_repo}`
4. Installed {len(installed)} compatible tool(s) into `.github/`
5. Generated categorised documentation in `.github/COPILOT_TOOLS.md`

### 📁 Changed directories

| Directory | Purpose |
|-----------|---------|
| `.github/instructions/` | Language & framework-specific Copilot instructions |
| `.github/agents/` | Custom Copilot agent definitions |
| `.github/prompts/` | Reusable prompt templates (skills) |
| `.github/COPILOT_TOOLS.md` | Auto-generated tool overview |

### ✅ Review checklist

- [ ] Inspect each new file for accuracy and relevance
- [ ] Read `.github/COPILOT_TOOLS.md` for the categorised overview
- [ ] Test tools with GitHub Copilot in VS Code
- [ ] Remove any tools that do not fit your workflow

---
*🤖 Generated by [repos-ai-tools-maintain](https://github.com/{maintenance_repo})*
"""


# ------------------------------------------------------------------ #
# Main                                                                 #
# ------------------------------------------------------------------ #


def main() -> None:
    github_token = os.environ.get("GITHUB_TOKEN")
    if not github_token:
        raise SystemExit("❌  GITHUB_TOKEN environment variable is required")

    repo_override = os.environ.get("REPO_OVERRIDE", "").strip()

    if repo_override:
        target_repo = repo_override
        secret_name = os.environ.get("TOKEN_SECRET_OVERRIDE", "").strip() or "TARGET_REPO_TOKEN"
    else:
        target_repo, secret_name = pick_target_repo()

    target_token = resolve_token(secret_name)
    logger.info("Target repository: %s  (token: %s)", target_repo, secret_name)

    api = GitHubAPI(target_token)

    try:
        repo_info = api.get_repo_info(target_repo)
    except Exception as exc:
        raise SystemExit(f"❌  Cannot access '{target_repo}': {exc}")

    default_branch = repo_info.get("default_branch", "main")

    # ── 1. Fetch trending repos ────────────────────────────────────────
    logger.info("Fetching GitHub trending repositories…")
    trending = fetch_trending_repos(github_token)
    if not trending:
        logger.warning("No trending repos returned. Exiting.")
        return
    logger.info("Found %d trending repos", len(trending))

    # ── 2. Scan each trending repo for Copilot tools ───────────────────
    candidates: list[dict] = []
    for repo in trending[:10]:
        full_name = repo["full_name"]
        logger.info("Scanning %s …", full_name)
        tools = fetch_repo_copilot_tools(full_name, github_token)
        if tools:
            logger.info("  └─ %d tool(s) found", len(tools))
            candidates.append({"repo": repo, "tools": tools})

    if not candidates:
        logger.info("No Copilot tools found in trending repos. Exiting.")
        return

    # ── 3. AI relevance analysis ───────────────────────────────────────
    logger.info("Running AI relevance analysis…")
    matched: list[dict] = []
    for item in candidates:
        relevant = analyze_tool_relevance(
            target_repo=target_repo,
            target_repo_info=repo_info,
            source_repo=item["repo"],
            tools=item["tools"],
            github_token=github_token,
        )
        matched.extend(relevant)

    if not matched:
        logger.info("No relevant tools found for %s. Exiting.", target_repo)
        return

    logger.info("%d relevant tool(s) selected for installation", len(matched))

    # ── 4. Clone → install → organize → PR ────────────────────────────
    today = datetime.date.today().isoformat()
    branch_name = f"copilot-tools/{today}"

    with tempfile.TemporaryDirectory() as tmpdir:
        clone_url = f"https://x-access-token:{target_token}@github.com/{target_repo}.git"
        logger.info("Cloning %s …", target_repo)
        _run(["git", "clone", "--depth=1", clone_url, tmpdir])
        _setup_git(tmpdir)

        _git(["checkout", "-b", branch_name], tmpdir)

        repo_path = Path(tmpdir)
        installed = install_tools(repo_path, matched)

        if not installed:
            logger.info("All selected tools already present. Nothing to commit.")
            return

        logger.info("Generating COPILOT_TOOLS.md…")
        organize_and_generate_readme(repo_path, github_token)

        _git(["add", ".github/"], tmpdir)

        if not _has_staged_changes(tmpdir):
            logger.info("No staged changes after add. Exiting.")
            return

        commit_msg = (
            f"chore: add {len(installed)} Copilot tool(s) from GitHub trending [{today}]\n\n"
            f"Co-authored-by: github-actions[bot] <{_BOT_EMAIL}>"
        )
        _git(["commit", "-m", commit_msg], tmpdir)

        logger.info("Pushing branch '%s'…", branch_name)
        _git(["push", "origin", branch_name], tmpdir)

        if api.pr_exists(target_repo, branch_name, default_branch):
            logger.info("PR already exists for branch '%s'. Skipping.", branch_name)
            return

        pr = api.create_pr(
            repo=target_repo,
            title=f"🤖 Add Copilot tools from GitHub trending [{today}]",
            body=_build_pr_body(installed, target_repo, today),
            head=branch_name,
            base=default_branch,
        )
        logger.info("✅  PR created: %s", pr["html_url"])


if __name__ == "__main__":
    main()
