"""每日 Copilot 工具发现工作流的主编排脚本。

调用链路：
  workflow setup job (pick_repo.py)
      → 读取 repos.json，构建全部目标仓库 matrix，推导 token secret 名
      → 通过 GITHUB_OUTPUT 传递给 run job

  workflow run job (main.py，即本文件)
      → 从环境变量读取 TARGET_REPO / RESOLVED_ORG_TOKEN / TARGET_REPO_TOKEN
      → 抓取 GitHub Trending → 扫描 Copilot 工具 → AI 判断相关性
      → 安装工具 → 生成 README → commit → push → 创建 PR
"""

from __future__ import annotations

import datetime
import logging
import os
import subprocess
import sys
import tempfile
from pathlib import Path

# 把同级目录加入模块搜索路径，使 import 不依赖工作目录
sys.path.insert(0, str(Path(__file__).parent))

from analyze_tools import analyze_tool_relevance
from fetch_trending import fetch_repo_copilot_tools, fetch_trending_repos
from github_api import GitHubAPI
from install_tools import install_tools
from organize_readme import organize_and_generate_readme

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)

# git commit 时使用 bot 身份，避免污染贡献者列表
_BOT_EMAIL = "github-actions[bot]@users.noreply.github.com"
_BOT_NAME = "github-actions[bot]"


# ------------------------------------------------------------------ #
# Helpers                                                              #
# ------------------------------------------------------------------ #


def _run(cmd: list[str], cwd: str | None = None) -> None:
    """执行任意 shell 命令，失败时抛出异常。"""
    subprocess.run(cmd, check=True, capture_output=True, cwd=cwd)


def _git(args: list[str], cwd: str) -> subprocess.CompletedProcess:
    """在指定目录执行 git 命令。"""
    return subprocess.run(["git", "-C", cwd, *args], check=True, capture_output=True)


def _setup_git(tmpdir: str) -> None:
    """配置 git 提交者身份为 github-actions bot。"""
    _git(["config", "user.email", _BOT_EMAIL], tmpdir)
    _git(["config", "user.name", _BOT_NAME], tmpdir)


def _has_staged_changes(tmpdir: str) -> bool:
    """返回 True 表示暂存区有待提交的变更。"""
    result = subprocess.run(
        ["git", "-C", tmpdir, "diff", "--cached", "--quiet"], capture_output=True
    )
    return result.returncode != 0  # 非零退出码 → 有变更


def _build_pr_body(installed: list[dict], target_repo: str, today: str) -> str:
    # GITHUB_REPOSITORY 是本维护仓库自身的名称（owner/repo 格式），
    # GitHub Actions 会自动注入此变量，用于在 PR 描述中生成"来源"链接。
    maintenance_repo = os.environ.get("GITHUB_REPOSITORY", "knewbeing/repos-ai-tools-maintain")
    rows = "\n".join(
        "| {emoji} `{name}` | {type} | [{src}](https://github.com/{src}) |".format(
            emoji={"instruction": "📋", "agent": "🤖", "skill": "⚡"}.get(t["type"], "📄"),
            name=t["name"],
            type=t["type"],
            src=t.get("source_repo", ""),
        )
        for t in installed
    )

    return f"""## 🤖 Automated Copilot Tools Update — {today}

This PR was automatically generated by the [daily Copilot tools maintenance workflow](https://github.com/{maintenance_repo}).

### 📦 Installed tools ({len(installed)})

| Tool | Type | Source |
|------|------|--------|
{rows}

### 🔍 Discovery process

1. Fetched the top 10 trending repositories on GitHub
2. Scanned each for Copilot tools (instructions, agents, prompts)
3. Used AI (GPT-4o-mini via GitHub Copilot API) to judge relevance for `{target_repo}`
4. Installed {len(installed)} compatible tool(s) into `.github/`
5. Generated categorised documentation in `.github/COPILOT_TOOLS.md`

### 📁 Changed directories

| Directory | Purpose |
|-----------|---------|
| `.github/instructions/` | Language & framework-specific Copilot instructions |
| `.github/agents/` | Custom Copilot agent definitions |
| `.github/prompts/` | Reusable prompt templates (skills) |
| `.github/COPILOT_TOOLS.md` | Auto-generated tool overview |

### ✅ Review checklist

- [ ] Inspect each new file for accuracy and relevance
- [ ] Read `.github/COPILOT_TOOLS.md` for the categorised overview
- [ ] Test tools with GitHub Copilot in VS Code
- [ ] Remove any tools that do not fit your workflow

---
*🤖 Generated by [repos-ai-tools-maintain](https://github.com/{maintenance_repo})*
"""


# ------------------------------------------------------------------ #
# Main                                                                 #
# ------------------------------------------------------------------ #


def main() -> None:
    # ── 环境变量说明 ────────────────────────────────────────────────────
    # GITHUB_TOKEN        : GitHub Actions 自动注入的临时安装令牌。
    #                       作用域仅限本维护仓库自身，无法访问任何其他仓库。
    #                       用途：GitHub API 只读调用（Trending 抓取兜底）。
    #
    # COPILOT_TOKEN       : 用于调用 GitHub Copilot API 的 PAT。
    #                       要求：PAT 所属账号开通 GitHub Copilot。
    #                       说明：GITHUB_TOKEN（Server-to-Server）不支持该 API 端点。
    #
    # TARGET_REPO         : 由 matrix 注入，格式 "owner/repo"，本次处理的目标仓库。
    #
    # RESOLVED_ORG_TOKEN  : 由 workflow 通过 secrets[matrix.token_env_name] 动态查找。
    #                       token_env_name 由 pick_repo.py 推导（如 ANOTHER_ORG_GITHUB_TOKEN）。
    #                       用于 clone/push/PR 目标仓库（需 repo 权限的 PAT）。
    #                       若该 secret 未注册则为空字符串。
    #
    # TARGET_REPO_TOKEN   : 通用兜底 PAT，RESOLVED_ORG_TOKEN 为空时使用。
    #
    # GITHUB_REPOSITORY   : 本维护仓库名（owner/repo），用于在 PR 描述中生成来源链接。
    #
    # 注意：GITHUB_TOKEN 的作用域仅限本仓库。
    #       即使目标仓库与本仓库属于同一 org/user，也无法用 GITHUB_TOKEN 访问。
    #       所有目标仓库的 git 操作（clone/push/PR）都必须使用 PAT。
    # ───────────────────────────────────────────────────────────────────

    github_token = os.environ.get("GITHUB_TOKEN")
    if not github_token:
        raise SystemExit("❌  GITHUB_TOKEN 环境变量缺失（GitHub Actions 应自动注入）")
    copilot_token = os.environ.get("COPILOT_TOKEN", "").strip()
    if not copilot_token:
        raise SystemExit(
            "❌  COPILOT_TOKEN 环境变量缺失。\n"
            "    请在本仓库 Settings → Secrets 中添加 COPILOT_TOKEN（PAT），\n"
            "    且该 PAT 所属账号需开通 GitHub Copilot。"
        )

    # TARGET_REPO 由 setup job 通过 GITHUB_OUTPUT 传递，再由 workflow env: 注入
    target_repo = os.environ.get("TARGET_REPO", "").strip()
    if not target_repo:
        raise SystemExit("❌  TARGET_REPO 环境变量缺失（应由 setup job 传入）")

    # ── Token 解析（两级优先级）────────────────────────────────────────
    #
    # GITHUB_TOKEN 的作用域仅限本仓库，任何外部目标仓库都必须使用 PAT。
    #
    # 1. RESOLVED_ORG_TOKEN：
    #    由 workflow 通过 secrets[matrix.token_env_name] 动态查找。
    #    token_env_name 约定为 <OWNER>_GITHUB_TOKEN（大写，连字符→下划线）。
    #    在本仓库 Settings → Secrets 中注册后自动生效，无需修改 workflow YAML。
    #
    # 2. TARGET_REPO_TOKEN：
    #    静态兜底 PAT，RESOLVED_ORG_TOKEN 未注册时使用。
    # ───────────────────────────────────────────────────────────────────
    target_owner = target_repo.split("/")[0].upper().replace("-", "_")
    target_token = (
        os.environ.get("RESOLVED_ORG_TOKEN", "").strip()    # 优先：<ORG>_GITHUB_TOKEN
        or os.environ.get("TARGET_REPO_TOKEN", "").strip()   # 兜底：TARGET_REPO_TOKEN
    )
    if not target_token:
        raise SystemExit(
            f"❌  找不到 '{target_repo}' 的访问 token。\n"
            f"    请在本仓库 Settings → Secrets 中添加 '{target_owner}_GITHUB_TOKEN'\n"
            f"    （PAT 需要 repo 权限），然后重新运行 workflow。"
        )

    logger.info("目标仓库: %s", target_repo)

    api = GitHubAPI(target_token)

    try:
        repo_info = api.get_repo_info(target_repo)
    except Exception as exc:
        raise SystemExit(f"❌  无法访问仓库 '{target_repo}': {exc}")

    default_branch = repo_info.get("default_branch", "main")

    # ── 步骤 1：抓取 GitHub Trending 前 10 仓库 ────────────────────────
    # 使用 GITHUB_TOKEN（只读）抓取，不需要写权限
    logger.info("正在抓取 GitHub Trending 仓库…")
    trending = fetch_trending_repos(github_token)
    if not trending:
        logger.warning("未获取到 Trending 仓库，退出。")
        return
    logger.info("获取到 %d 个 Trending 仓库", len(trending))

    # ── 步骤 2：扫描每个 Trending 仓库中的 Copilot 工具文件 ────────────
    # 扫描 .github/instructions/ .github/agents/ .github/prompts/ 等目录
    candidates: list[dict] = []
    for repo in trending[:10]:
        full_name = repo["full_name"]
        logger.info("扫描 %s …", full_name)
        tools = fetch_repo_copilot_tools(full_name, github_token)
        if tools:
            logger.info("  └─ 发现 %d 个工具文件", len(tools))
            candidates.append({"repo": repo, "tools": tools})

    if not candidates:
        logger.info("Trending 仓库中未发现 Copilot 工具，退出。")
        return

    # ── 步骤 3：AI 相关性分析 ──────────────────────────────────────────
    # 调用 GitHub Copilot API (GPT-4o-mini) 判断工具是否适合目标仓库
    # 使用 COPILOT_TOKEN（PAT）鉴权
    logger.info("正在进行 AI 相关性分析…")
    matched: list[dict] = []
    for item in candidates:
        relevant = analyze_tool_relevance(
            target_repo=target_repo,
            target_repo_info=repo_info,
            source_repo=item["repo"],
            tools=item["tools"],
            copilot_token=copilot_token,
        )
        matched.extend(relevant)

    if not matched:
        logger.info("未找到适合 %s 的工具，退出。", target_repo)
        return

    logger.info("共选出 %d 个相关工具准备安装", len(matched))

    # ── 步骤 4：clone → 安装工具 → 生成 README → commit → push → PR ───
    # 以下操作全部使用 target_token（有写权限的 PAT）
    today = datetime.date.today().isoformat()
    branch_name = f"copilot-tools/{today}"

    with tempfile.TemporaryDirectory() as tmpdir:
        # 使用 PAT 拼接认证 URL，实现无交互 clone
        clone_url = f"https://x-access-token:{target_token}@github.com/{target_repo}.git"
        logger.info("正在 clone %s …", target_repo)
        _run(["git", "clone", "--depth=1", clone_url, tmpdir])
        _setup_git(tmpdir)

        # 创建独立分支，避免直接修改默认分支
        _git(["checkout", "-b", branch_name], tmpdir)

        repo_path = Path(tmpdir)

        # 将匹配到的工具文件写入目标仓库的 .github/ 目录
        installed = install_tools(repo_path, matched)

        if not installed:
            logger.info("所有工具已存在，无需重复安装。")
            return

        # 调用 AI（GPT-4o）扫描已安装的工具并生成分类说明文档
        logger.info("正在生成 COPILOT_TOOLS.md…")
        organize_and_generate_readme(repo_path, copilot_token)

        _git(["add", ".github/"], tmpdir)

        if not _has_staged_changes(tmpdir):
            logger.info("暂存区无变更，退出。")
            return

        commit_msg = (
            f"chore: add {len(installed)} Copilot tool(s) from GitHub trending [{today}]\n\n"
            f"Co-authored-by: github-actions[bot] <{_BOT_EMAIL}>"
        )
        _git(["commit", "-m", commit_msg], tmpdir)

        logger.info("正在推送分支 '%s'…", branch_name)
        _git(["push", "origin", branch_name], tmpdir)

        # 检查是否已有同名分支的 PR，避免重复创建
        if api.pr_exists(target_repo, branch_name, default_branch):
            logger.info("分支 '%s' 已存在 PR，跳过创建。", branch_name)
            return

        # 使用 target_token 在目标仓库创建 PR
        pr = api.create_pr(
            repo=target_repo,
            title=f"🤖 Add Copilot tools from GitHub trending [{today}]",
            body=_build_pr_body(installed, target_repo, today),
            head=branch_name,
            base=default_branch,
        )
        logger.info("✅  PR 已创建: %s", pr["html_url"])


if __name__ == "__main__":
    main()
